import { Camera2D, openFullscreen, KeyManager } from "../Game/Game.js";
import { Vector3D } from "../Matrix/Matrix.js";
import { Axis3DGroup, MeshRenderingProgram, MeshFillerProgram } from "./webglCapsules.js";
import { Camera3D } from "../Game3D/Game3D.js";
import { WebGLMan, WebProgram, TexExamples } from "./webglMan.js";
export declare class DetailedParser {
    static GlobalContext: {
        MeshRenderingProgram: typeof MeshRenderingProgram;
        MeshFillerProgram: typeof MeshFillerProgram;
        Axis3DGroup: typeof Axis3DGroup;
        Camera3D: typeof Camera3D;
        Vector3D: typeof Vector3D;
        KeyManager: typeof KeyManager;
        openFullscreen: typeof openFullscreen;
        addFunc: (fun: any) => void;
        W: number;
        H: number;
        gl: WebGL2RenderingContext;
        keypress: {
            a: boolean;
            w: boolean;
            s: boolean;
            d: boolean;
            up: boolean;
            down: boolean;
            right: boolean;
            left: boolean;
            ctrl: boolean;
            shift: boolean;
            space: boolean;
            q: boolean;
            e: boolean;
            t: boolean;
            g: boolean;
            r: boolean;
            f: boolean;
            i: boolean;
            o: boolean;
            h: boolean;
            y: boolean;
            p: boolean;
            m: boolean;
            n: boolean;
            b: boolean;
            v: boolean;
            c: boolean;
            x: boolean;
            z: boolean;
            u: boolean;
            l: boolean;
            j: boolean;
            Enter: boolean;
            Backspace: boolean;
            listen: () => void;
            Hor: () => number;
            Ver: () => number;
            Horizontal: () => number;
            Vertical: () => number;
            Depth: () => number;
            mv2D: (vel?: number) => import("../Matrix/Matrix.mjs").Vector2D;
            mv3D: (vel?: number) => import("../Matrix/Matrix.mjs").Vector3D;
            createSwitch: (k1: string, k2: string) => () => number;
        };
        mousepos: {
            x: number;
            y: number;
            lastid: string;
        };
        mouseclick: boolean[];
        cam: Camera2D | Camera3D;
        WebProgram: typeof WebProgram;
        WebGLMan: typeof WebGLMan;
        TexExamples: TexExamples;
    };
    static ObjectRegistry: Record<string, (params: Map<string | number, any>, gl: WebGL2RenderingContext) => any>;
    static prepareMathFunction: (callbackString: any) => (...callArgs: any[]) => any;
    static FunctionRegistry: Record<string, (params: Map<string | number, any>, gl: WebGL2RenderingContext) => any>;
    static context: {
        vars: Map<string, any>;
        lookUpNames: any[] & {
            add: (obj: any, ...names: string[]) => void;
        };
        blockName: string[];
        isBlockAsync: boolean;
        blockParams: ({
            name: string;
            start: string;
            end: string;
            type: string;
            value?: undefined;
        } | {
            name: string;
            value: string;
            type: string;
            start?: undefined;
            end?: undefined;
        })[];
        lastUsedProgram: WebProgram | null;
        thiscontext: any;
    };
    static get lastUsedProgram(): any;
    static set lastUsedProgram(p: any);
    static get lastFillerProgram(): any;
    static set lastFillerProgram(p: any);
    static getVar(name: string): any;
    static joinIndentedLines(lines: string[]): string[];
    static parseBlockParams(raw: string | undefined): ({
        name: string;
        start: string;
        end: string;
        type: string;
        value?: undefined;
    } | {
        name: string;
        value: string;
        type: string;
        start?: undefined;
        end?: undefined;
    })[];
    static currentBlockContent: string[];
    static parse(str: string, gl: WebGL2RenderingContext, thiscontext: any): Promise<void>;
    static prepareAction(line: string): (() => void) | null;
    private static createSimpleAction;
    private static createCallAction;
    static chooseActionForLine(code: string): Promise<() => void>;
    static compileJsBlock(code: string, ifConditions?: string[]): Promise<() => Promise<void>>;
    static executeEvalBlock(code: string): void;
    static get ctx(): {
        vars: Map<string, any>;
        lookUpNames: any[] & {
            add: (obj: any, ...names: string[]) => void;
        };
        blockName: string[];
        isBlockAsync: boolean;
        blockParams: ({
            name: string;
            start: string;
            end: string;
            type: string;
            value?: undefined;
        } | {
            name: string;
            value: string;
            type: string;
            start?: undefined;
            end?: undefined;
        })[];
        lastUsedProgram: WebProgram;
        thiscontext: any;
    };
    static get gctx(): {
        MeshRenderingProgram: typeof MeshRenderingProgram;
        MeshFillerProgram: typeof MeshFillerProgram;
        Axis3DGroup: typeof Axis3DGroup;
        Camera3D: typeof Camera3D;
        Vector3D: typeof Vector3D;
        KeyManager: typeof KeyManager;
        openFullscreen: typeof openFullscreen;
        addFunc: (fun: any) => void;
        W: number;
        H: number;
        gl: WebGL2RenderingContext;
        keypress: {
            a: boolean;
            w: boolean;
            s: boolean;
            d: boolean;
            up: boolean;
            down: boolean;
            right: boolean;
            left: boolean;
            ctrl: boolean;
            shift: boolean;
            space: boolean;
            q: boolean;
            e: boolean;
            t: boolean;
            g: boolean;
            r: boolean;
            f: boolean;
            i: boolean;
            o: boolean;
            h: boolean;
            y: boolean;
            p: boolean;
            m: boolean;
            n: boolean;
            b: boolean;
            v: boolean;
            c: boolean;
            x: boolean;
            z: boolean;
            u: boolean;
            l: boolean;
            j: boolean;
            Enter: boolean;
            Backspace: boolean;
            listen: () => void;
            Hor: () => number;
            Ver: () => number;
            Horizontal: () => number;
            Vertical: () => number;
            Depth: () => number;
            mv2D: (vel?: number) => import("../Matrix/Matrix.mjs").Vector2D;
            mv3D: (vel?: number) => import("../Matrix/Matrix.mjs").Vector3D;
            createSwitch: (k1: string, k2: string) => () => number;
        };
        mousepos: {
            x: number;
            y: number;
            lastid: string;
        };
        mouseclick: boolean[];
        cam: Camera2D | Camera3D;
        WebProgram: typeof WebProgram;
        WebGLMan: typeof WebGLMan;
        TexExamples: TexExamples;
    };
    static parseValue(valueString: string): any;
    static parseObjectDef(line: string): Promise<boolean>;
    static executeChain(baseObj: any, chainParts: string[]): any;
    static splitChain(methodsString: string): string[];
    static parseFncCall(line: string): boolean;
    static prepareChainAction(line: string): () => void;
}
