import { Matrix2D, Matrix3D, Matrix4D, Vector } from "../Matrix/Matrix.js";
export declare class WebGLMan {
    gl: WebGL2RenderingContext;
    dirPath?: string;
    static stWebGLMan: WebGLMan;
    programs: any[];
    constructor(gl?: WebGL2RenderingContext, dirPath?: string);
    static setGL(gl: WebGL2RenderingContext, path?: string): typeof WebGLMan;
    static get gl(): WebGL2RenderingContext;
    static get programs(): WebProgram[];
    static get dirPath(): string;
    static set gl(gl: WebGL2RenderingContext);
    static set programs(programs: WebProgram[]);
    static set dirPath(dirPath: string);
    static program(ID?: number, vertPath?: string, fragPath?: string): WebProgram;
    program(ID?: number, vertPath?: string, fragPath?: string): WebProgram;
    static includeExternalProgram(p: WebProgram): WebProgram;
    static getProgramByID(ID: number): WebProgram;
    getProgramByID(ID: number): WebProgram;
}
export type UNUM = (WebGLUniformLocation & {
    set: (num: number) => UNUM;
});
export type UVEC = (WebGLUniformLocation & {
    set: (vec: Vector | number[], offset?: any, len?: any) => UVEC;
});
export type UMAT2 = (WebGLUniformLocation & {
    set: (mat: Matrix2D | number[] | Float32Array, transpose?: boolean, offset?: any, len?: any) => UMAT2;
});
export type UMAT3 = (WebGLUniformLocation & {
    set: (mat: Matrix3D | number[] | Float32Array, transpose?: boolean, offset?: any, len?: any) => UMAT3;
});
export type UMAT4 = (WebGLUniformLocation & {
    set: (mat: Matrix4D | number[] | Float32Array, transpose?: boolean, offset?: any, len?: any) => UMAT4;
});
export declare class WebProgram {
    gl: WebGL2RenderingContext;
    vertPath: string;
    fragPath: string;
    program: WebGLProgram;
    ID: number;
    vert: WebGLShader;
    frag: WebGLShader;
    nUsedTextures: number;
    standardTEXW: number;
    standardTEXH: number;
    viewportW: number;
    viewportH: number;
    uniforms: Map<string, UNUM | UVEC | UMAT2 | UMAT3 | UMAT4>;
    constructor(gl: WebGL2RenderingContext, vertPath?: string, fragPath?: string);
    loadProgram(vp?: string, fp?: string): Promise<this>;
    use(): this;
    isWebProgram(): boolean;
    includeInWebManList(): this;
    VAOs: VAO[];
    currentVAO: number;
    get VAO(): VAO;
    createVAO(): VAO;
    bindVAO(number?: number): this;
    unbindVAO(): this;
    static Textures: BindableTexture[];
    createTexture2D(name?: string, size?: [number, number] | number[], format?: [number, number] | number[] | TexExamples, data?: any, FILTER_WRAP?: ["NEAREST" | "LINEAR" | number, "NEAREST" | "LINEAR" | number, "CLAMP" | "REPEAT" | "MIRROR" | number, "CLAMP" | "REPEAT" | "MIRROR" | number], texUnit?: TextureUnitType, LODlevel?: number): BindableTexture;
    texture2D(params?: {
        name?: string;
        size?: [number, number] | number[];
        format?: [number, number] | number[] | TexExamples;
        data?: any;
        FILTER_WRAP?: ["NEAREST" | "LINEAR" | number, "NEAREST" | "LINEAR" | number, "CLAMP" | "REPEAT" | "MIRROR" | number, "CLAMP" | "REPEAT" | "MIRROR" | number];
        texUnit?: TextureUnitType;
        LODlevel?: any;
    }): BindableTexture;
    loadLongArray2GPUTextures(array: Float32Array, basename: string, startTextureUnit: TextureUnitType, format?: [number, number] | number[] | TexExamples, FILTER_WRAP?: ["NEAREST" | "LINEAR" | number, "NEAREST" | "LINEAR" | number, "CLAMP" | "REPEAT" | "MIRROR" | number, "CLAMP" | "REPEAT" | "MIRROR" | number]): {
        startTextureUnit: number;
        lastTexureUnit: number;
        maxLength: any;
        nextTexureUnit: number;
        setLengthUniforms: () => any;
    };
    texture2DFromImage(img: HTMLImageElement, name: string, format?: [number, number] | number[] | TexExamples, FILTER_WRAP?: ["NEAREST" | "LINEAR" | number, "NEAREST" | "LINEAR" | number, "CLAMP" | "REPEAT" | "MIRROR" | number, "CLAMP" | "REPEAT" | "MIRROR" | number], texUnit?: TextureUnitType, LODlevel?: number): BindableTexture;
    bindTextureUnit2Uniform(texUnit: number, name: string): this;
    getTextureFromUnit(texUnit: TextureUnitType | number): any;
    uTexUnit(texUnit: number, name: string): this;
    bindNewTexture(tex: WebGLTexture, name: string): number;
    bindTexture(tex: WebGLTexture, name: string, nTexture?: TextureUnitType): number;
    bindTexName2TexUnit(name: string, nTexture?: TextureUnitType): this;
    createTexture2DArray(name?: string, size?: [number, number, number] | number[], format?: [number, number] | number[] | TexExamples, data?: any, FILTER_WRAP?: ["NEAREST" | "LINEAR" | number, "NEAREST" | "LINEAR" | number, "CLAMP" | "REPEAT" | "MIRROR" | number, "CLAMP" | "REPEAT" | "MIRROR" | number], texUnit?: TextureUnitType, MIPlevel?: number): BindableTexture3D;
    texture2DArray(params?: {
        name?: string;
        size?: [number, number, number] | number[];
        format: [number, number] | number[] | TexExamples;
        data?: any;
        FILTER_WRAP?: ["NEAREST" | "LINEAR" | number, "NEAREST" | "LINEAR" | number, "CLAMP" | "REPEAT" | "MIRROR" | number, "CLAMP" | "REPEAT" | "MIRROR" | number];
        texUnit?: TextureUnitType;
        MIPlevel?: number;
    }): BindableTexture3D;
    uMat4(name: string): UMAT4;
    uMat3(name: string): UMAT3;
    uMat2(name: string): UMAT2;
    uVec(name: string, dimension?: number, isFloat?: boolean, isUnsignedInt?: boolean): UVEC;
    uNum(name: string, isFloat?: boolean, isUnsignedInt?: boolean): UNUM;
    uFloat(name: string): UNUM;
    uInt(name: string): UNUM;
    cFrameBuffer(): FrameBuffer;
    unbindFrameBuffer(): this;
    unbindFBO(): this;
    setViewport(xoff?: number, yoff?: number, w?: number, h?: number): this;
    clearBuffer(type: "COLOR" | "DEPTH" | "STENCIL"): this;
    clear(type: "COLOR" | "DEPTH" | "STENCIL"): this;
    clearMask(type: "COLOR" | "DEPTH" | "STENCIL"): this;
    clearColor(color?: string | number[]): this;
    clearDepth(depthValue?: number): this;
    clearStencil(stencilValue?: number): this;
    isDepthTest: boolean;
    depthFunction: "NEVER" | "LESS" | "EQUAL" | "LEQUAL" | "GREATER" | "NOTEQUAL" | "GEQUAL" | "ALWAYS";
    protected initDepthBefDraw(): void;
    drawArrays(mode: GLMode, vaoOff?: number, vertexCount?: any, instanceCount?: number): this;
    drawElements(mode: GLMode, elementCount?: number, type?: "UNSIGNED_BYTE" | "UNSIGNED_SHORT" | "UNSIGNED_INT", eboOff?: number, instanceCount?: number): this;
    blendEquation(mode?: "ADD" | "SUBSTRACT" | "REVERSE_SUBSTRACT" | "MIN" | "MAX"): void;
    blendFunc(sfactor?: BlendConstantType, dfactor?: BlendConstantType): void;
    blendColor(r: number, g: number, b: number, a: number): void;
    finish(): this;
}
export type BlendConstantType = "ZERO" | "ONE" | "SRC_COLOR" | "ONE_MINUS_SRC_COLOR" | "DST_COLOR" | "ONE_MINUS_DST_COLOR" | "SRC_ALPHA" | "ONE_MINUS_SRC_ALPHA" | "DST_ALPHA" | "ONE_MINUS_DST_ALPHA" | "CONSTANT_COLOR" | "ONE_MINUS_CONSTANT_COLOR" | "CONSTANT_ALPHA" | "ONE_MINUS_CONSTANT_ALPHA" | "ONE_MINUS_CONSTANT_ALPHA";
export type TextureUnitType = number | "TexUnit0" | "TexUnit1" | "TexUnit2" | "TexUnit3" | "TexUnit4" | "TexUnit5" | "TexUnit6" | "TexUnit7" | "TexUnit8" | "TexUnit9" | "TexUnit10" | "TexUnit11" | "TexUnit12" | "TexUnit13" | "TexUnit14" | "TexUnit15" | "TexUnit16" | "TexUnit17" | "TexUnit18" | "TexUnit19" | "TexUnit20" | "TexUnit21" | "TexUnit22" | "TexUnit23" | "TexUnit24" | "TexUnit25" | "TexUnit26" | "TexUnit27" | "TexUnit28" | "TexUnit29" | "TexUnit30" | "TexUnit31";
export declare function parseTexUnitType(texUnit: TextureUnitType): number;
export type ColorAttachmentType = Range<16> | "ColAtch0" | "ColAtch1" | "ColAtch2" | "ColAtch3" | "ColAtch4" | "ColAtch5" | "ColAtch6" | "ColAtch7" | "ColAtch8" | "ColAtch9" | "ColAtch10" | "ColAtch11" | "ColAtch12" | "ColAtch13" | "ColAtch14" | "ColAtch15";
export declare function parseColAtchType(colAttachment: ColorAttachmentType): Range<16>;
export declare class FrameBuffer {
    gl: WebGL2RenderingContext;
    program?: WebProgram;
    protected fbo: WebGLFramebuffer;
    colorBuffersUsed: boolean[];
    constructor(gl: WebGL2RenderingContext, program?: WebProgram);
    bind(colorATTACHMENTS?: ColorAttachmentType[]): this;
    unbind(): this;
    drawBuffers(unitArr?: ColorAttachmentType[]): this;
    bindColorBuffer(texture: WebGLTexture, colorUnit?: ColorAttachmentType, LODlevel?: number): this;
    unbindBuffer(colorUnit: ColorAttachmentType): void;
    readColorAttachment(n: ColorAttachmentType, x: number, y: number, w: number, h: number, format: TexExamples | [number, number, number], dimension?: number): Float32Array;
    readColAttchTexture(tex: WebGLTexture, dimension?: number, x?: any, y?: any, w?: any, h?: any, format?: TexExamples | [number, number, number], colUnit?: ColorAttachmentType): Float32Array;
    colorMask(r?: boolean, g?: boolean, b?: boolean, a?: boolean): this;
    bindTextureDepthBuffer(texture: WebGLTexture, LODlevel?: number): this;
    depthMask(depth: boolean): this;
    cRenderBuffer(type?: "DEPTH" | "COLOR" | "STENCIL_INDEX8" | "DEPTH_STENCIL", quality?: "low" | "medium" | "high", w?: number, h?: number, colorUnit?: ColorAttachmentType): WebGLRenderbuffer;
    stencilMask(maskNum: number): this;
    get _(): WebGLFramebuffer;
}
export type GLMode = "TRIANGLES" | "TRIANGLE_STRIP" | "TRIANGLE_FAN" | "POINTS" | "LINES" | "LINE_STRIP" | "LINE_LOOP";
export type BindableTexture = WebGLTexture & {
    unit: number;
    w: number;
    h: number;
    fill: (arr: any, x?: number, y?: number, w?: number, h?: number, LOD?: number) => BindableTexture;
    bind: (textureUnit?: TextureUnitType) => BindableTexture;
    unbind: (textureUnit?: TextureUnitType) => BindableTexture;
};
export type BindableTexture3D = WebGLTexture & {
    unit: number;
    w: number;
    h: number;
    fill: (arr: any, x?: number, y?: number, z?: number, w?: number, h?: number, d?: number, LOD?: number) => BindableTexture3D;
    bind: (textureUnit?: TextureUnitType) => BindableTexture3D;
    unbind: (textureUnit?: TextureUnitType) => BindableTexture3D;
    setLengthUniforms: () => BindableTexture3D;
};
export type TexExamples = {
    "RFloat": [number, number, number];
    "RGFloat": [number, number, number];
    "RGBFloat": [number, number, number];
    "RGBAFloat": [number, number, number];
    "RFloat16": [number, number, number];
    "RGFloat16": [number, number, number];
    "RGBFloat16": [number, number, number];
    "RGBAFloat16": [number, number, number];
    "R": [number, number, number];
    "RG": [number, number, number];
    "RGB": [number, number, number];
    "RGBA": [number, number, number];
    "RInt": [number, number, number];
    "RGInt": [number, number, number];
    "RGBInt": [number, number, number];
    "RGBAInt": [number, number, number];
    "RInt16": [number, number, number];
    "RGInt16": [number, number, number];
    "RGBInt16": [number, number, number];
    "RGBAInt16": [number, number, number];
    "RInt8": [number, number, number];
    "RGInt8": [number, number, number];
    "RGBInt8": [number, number, number];
    "RGBAInt8": [number, number, number];
    "RUInt": [number, number, number];
    "RGUInt": [number, number, number];
    "RGBUInt": [number, number, number];
    "RGBAUInt": [number, number, number];
    "RUInt16": [number, number, number];
    "RGUInt16": [number, number, number];
    "RGBUInt16": [number, number, number];
    "RGBAUInt16": [number, number, number];
    "RUInt8": [number, number, number];
    "RGUInt8": [number, number, number];
    "RGBUInt8": [number, number, number];
    "RGBAUInt8": [number, number, number];
    "RUBYTE8": [number, number, number];
    "RGUBYTE8": [number, number, number];
    "RGBUBYTE8": [number, number, number];
    "RGBAUBYTE8": [number, number, number];
};
export declare var TexExamples: TexExamples;
export declare class VAO {
    gl: WebGL2RenderingContext;
    program: WebGLProgram;
    protected vao: WebGLVertexArrayObject;
    vaoLength: number;
    eboLength: number;
    constructor(gl: WebGL2RenderingContext, program: WebGLProgram);
    bind(): this;
    cVBO(name: string, data: Float32Array, dimension?: number, type?: "FLOAT" | "UNSIGNED_BYTE", stride?: number, offset?: number, normalized?: boolean): WebGLBuffer;
    attribute(name: string, data: Float32Array | number[], dimension?: number, type?: "FLOAT" | "UNSIGNED_BYTE", stride?: number, offset?: number, normalized?: boolean): WebGLBuffer;
    cEBO(indices: Float32Array): WebGLBuffer[];
    copyBufferFromGPU(src: WebGLBuffer, dst: WebGLBuffer, nBytes: any, rdOff?: number, wrOff?: number): WebGLBuffer;
    get _(): WebGLVertexArrayObject;
}
export type Range<N extends number, Result extends unknown[] = []> = Result['length'] extends N ? Result[number] : Range<N, [...Result, Result['length']]>;
export declare function wrapGL(gl: any): any;
